#!/bin/bash
for i in {1..10}
do
  echo " "
  echo "aes256 1KB upload test $i :"
  time cat 1KB.bin | python FTclient.py write 1KB.bin localhost:8000 aes256 passpass
done

for i in {1..10}
do
  echo " "
  echo "aes256 1MB upload test $i :"
  time cat 1MB.bin | python FTclient.py write 1MB.bin localhost:8000 aes256 passpass
done

for i in {1..10}
do
  echo " "
  echo "aes256 1GB upload test $i :"
  time cat 1GB.bin | python FTclient.py write 1GB.bin localhost:8000 aes256 passpass
done

for i in {1..10}
do
  echo " "
  echo "aes128 1KB upload test $i :"
  time cat 1KB.bin | python FTclient.py write 1KB.bin localhost:8000 aes128 passpass
done

for i in {1..10}
do
  echo " "
  echo "aes128 1MB upload test $i :"
  time cat 1MB.bin | python FTclient.py write 1MB.bin localhost:8000 aes128 passpass
done

for i in {1..10}
do
  echo " "
  echo "aes128 1GB upload test $i :"
  time cat 1GB.bin | python FTclient.py write 1GB.bin localhost:8000 aes128 passpass
done

for i in {1..10}
do
  echo " "
  echo "null 1KB upload test $i :"
  time cat 1KB.bin | python FTclient.py write 1KB.bin localhost:8000 null passpass
done

for i in {1..10}
do
  echo " "
  echo "null 1MB upload test $i :"
  time cat 1MB.bin | python FTclient.py write 1MB.bin localhost:8000 null passpass
done

for i in {1..10}
do
  echo " "
  echo "null 1GB upload test $i :"
  time cat 1GB.bin | python FTclient.py write 1GB.bin localhost:8000 null passpass
done
